### ISSUE TITLE
why do you include the node_modules + content

### ISSUE THREAD

**Issue by 2075** [Artificial-Engineering/node-sdl-runtime#2]
...if you rm -rf it upon launch of configure.sh?
with a proper package.json it should be okay to remove the node_modules form the repo, i reckon.

**Comment by 2075** [comment]
(jaja, i know, me moaning all the time :) )

**Comment by cookiengineer** [comment]
Hm?

As of my knowledge, node-gyp will not run if not all source codes are available. npm has no binary support, therefore all source codes must be available for the node-gyp rebuild run.

**Comment by 2075** [comment]
yes, but before npm i, you rm -rf the node_modules, so you wouldnt need them in the repo. or you remove the sudo rm -rf. anyway, not so important, jsut a thought in terms of reducing bloat :)
```
sudo rm -rf ./node_modules;
npm install; <- creates node_modules, if non existent
cd node_modules/ffi;
node-gyp rebuild;
```

**Comment by cookiengineer** [comment]
Bindings are now more minimalistic. So this can be closed.
